title: mullvad
email: dave@dave.io
lang: en-GB
description: >-
  Docuementation for the mullvad command-line utility by Dave Williams
baseurl: /
url: https://mullvad.dave.io
twitter_username: syn
github_username: daveio
git_address: https://github.com/daveio/mullvad
git_edit_address: https://github.com/daveio/mullvad/blob/main
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
bootwatch: darkly # cerulean cosmo custom cyborg darkly flatly journal lumen paper readable sandstone simplex slate solar spacelab superhero united yeti
markdown: kramdown
highlighter: rouge
timezone: Europe/London
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      sectionid: blog
  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
      sectionid: docs
      seo:
        type: WebPage
collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
exclude:
  - _theme/
  - .idea/
  - .jekyll-cache/
  - .sass-cache/
  - node_modules/
  - vendor
  - vendor/bundle/
  - vendor/bundle/ruby/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
