[tool.poetry]
name = "mullvad"
version = "0.1.0"
description = ""
authors = ["Dave Williams <dave@dave.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
